name: Deploy to Amazon ECS
on: 
  push:
    branches:
      - main

env:
  AWS_REGION: "us-west-2"  
  SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
  REMOTE_HOST: ${ { secrets.HOST_DNS }}
  REMOTE_USER: ${ { secrets.USERNAME }}
  TARGET: ${ { secrets.TARGET_DIR }}                  

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Build image
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.key }}
        port: ${{ secrets.PORT }} 
        script: |
          docker build -t estl engineering-assessment-main/.
  
  deploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build image
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.key }}
        port: ${{ secrets.PORT }} 
        script: |
          docker run -d -it --name app estl
  